minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
trustLockfile: false
strictDepBuilds: true
allowBuilds:
  esbuild: true
  workerd: true
  sharp: true
  fsevents: true
overrides:
  miniflare>sharp: 0.35.4
