import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { WebStandardStreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js";
import { CfWorkerJsonSchemaValidator } from "@modelcontextprotocol/sdk/validation/cfworker-provider.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import { ApiError, authorizeRequest, handleApi, validateOrigin, type Bindings, type Principal } from "./api.ts";
import { schemas, resultSchema, tokenSchema } from "./validation.ts";

const idSchema = z.string().min(1).max(100).regex(/^[a-zA-Z0-9_-]+$/);
const pagination = {
    limit: z.number().int().min(1).max(200).optional().describe("Page size; defaults to 50."),
    offset: z.number().int().min(0).optional().describe("Zero-based offset; defaults to 0."),
    q: z.string().max(200).optional().describe("Search the stored record contents."),
};
const maxBodyBytes = 600000;

// Only fixed tool definitions can reach the internal business adapter. This is
// an in-process call: no HTTP request or credential is sent to another service.
function createServer(request: Request, env: Bindings, principal: Principal) {
    const server = new McpServer({ name: "FlowMaster", version: "2.0.0" }, {
        jsonSchemaValidator: new CfWorkerJsonSchemaValidator(),
        instructions: "Manage a shared research workspace. Read current revisions before updates. Record actual experiment results with results_create. This server does not call models or run experiments.",
    });
    const invoke = async (path: string, method = "GET", data?: unknown): Promise<CallToolResult> => {
        const url = new URL(`/api/v1${path}`, request.url);
        const internal = new Request(url, {
            method,
            headers: { "Content-Type": "application/json" },
            ...(data === undefined ? {} : { body: JSON.stringify(data) }),
            signal: request.signal,
        });
        const response = await handleApi(internal, env, principal);
        const payload = await response.json() as Record<string, unknown>;
        const total = response.headers.get("X-Total-Count");
        if (total !== null) payload.total = Number(total);
        if (!response.ok) payload.status = response.status;
        return {
            content: [{ type: "text", text: JSON.stringify(payload) }],
            structuredContent: payload,
            ...(response.ok ? {} : { isError: true }),
        };
    };
    const readOnly = { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false };
    const create = { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false };
    const update = { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false };

    server.registerTool("workspace_get", {
        description: "Read the shared workspace snapshot (read permission). For workspaces above 5,000 records or the size limit, use collection list tools.",
        inputSchema: {}, annotations: readOnly,
    }, () => invoke("/workspace"));
    server.registerTool("workspace_seed", {
        description: "Import example research into an empty workspace only (admin permission). Existing data is never replaced.",
        inputSchema: {}, annotations: create,
    }, () => invoke("/seed", "POST"));

    for (const collection of ["projects", "hypotheses", "experiments", "resources"] as const) {
        const listInput = z.object({
            ...pagination,
            ...(collection === "hypotheses" || collection === "resources" ? { projectId: idSchema.optional() } : {}),
        }).strict();
        server.registerTool(`${collection}_list`, {
            description: `List ${collection} with pagination and optional search (read permission). Returns data and total.`,
            inputSchema: listInput, annotations: readOnly,
        }, args => {
            const query = new URLSearchParams();
            for (const [key, value] of Object.entries(args)) if (value !== undefined) query.set(key, String(value));
            return invoke(`/${collection}?${query}`);
        });
        server.registerTool(`${collection}_get`, {
            description: `Read one ${collection} record including its latest revision (read permission).`,
            inputSchema: { id: idSchema }, annotations: readOnly,
        }, ({ id }) => invoke(`/${collection}/${id}`));
        server.registerTool(`${collection}_create`, {
            description: `Create a ${collection} record (write permission). An omitted record ID is generated by the server.`,
            inputSchema: { data: schemas[collection] }, annotations: create,
        }, ({ data }) => invoke(`/${collection}`, "POST", data));
        server.registerTool(`${collection}_update`, {
            description: `Replace a ${collection} record (write permission). Supply the full data and its latest revision; stale or missing revisions are rejected.`,
            inputSchema: { id: idSchema, data: schemas[collection] }, annotations: update,
        }, ({ id, data }) => invoke(`/${collection}/${id}`, "PUT", data));
        server.registerTool(`${collection}_delete`, {
            description: `Delete a ${collection} record (write permission). Projects must be empty; deleting a hypothesis also deletes its experiments.`,
            inputSchema: { id: idSchema }, annotations: update,
        }, ({ id }) => invoke(`/${collection}/${id}`, "DELETE"));
    }
    server.registerTool("results_create", {
        description: "Record an actual experiment result and atomically update its hypothesis node (write permission). Does not execute experiments or call models. Do not retry blindly after an uncertain response.",
        inputSchema: { hypothesisId: idSchema, data: resultSchema }, annotations: update,
    }, ({ hypothesisId, data }) => invoke(`/hypotheses/${hypothesisId}/results`, "POST", data));
    server.registerTool("tokens_list", {
        description: "List access token metadata without token values (admin permission).",
        inputSchema: {}, annotations: readOnly,
    }, () => invoke("/tokens"));
    server.registerTool("tokens_create", {
        description: "Issue a read, write, or admin access token (admin permission). The token is returned only once; keep it private.",
        inputSchema: { data: tokenSchema }, annotations: create,
    }, ({ data }) => invoke("/tokens", "POST", data));
    server.registerTool("tokens_revoke", {
        description: "Revoke an access token immediately (admin permission).",
        inputSchema: { id: idSchema }, annotations: update,
    }, ({ id }) => invoke(`/tokens/${id}`, "DELETE"));
    return server;
}

function rpcError(status: number, code: number, message: string, data?: unknown): Response {
    return Response.json({ jsonrpc: "2.0", id: null, error: { code, message, ...(data === undefined ? {} : { data }) } }, { status });
}

async function readMessage(request: Request): Promise<unknown> {
    if (Number(request.headers.get("Content-Length")) > maxBodyBytes) throw new ApiError(413, "PAYLOAD_TOO_LARGE", "MCP 请求超过 600 KB 限制");
    const reader = request.body?.getReader();
    if (!reader) throw new SyntaxError("Empty JSON body");
    const chunks: Uint8Array[] = [];
    let size = 0;
    try {
        for (;;) {
            const { value, done } = await reader.read();
            if (done) break;
            size += value.byteLength;
            if (size > maxBodyBytes) {
                await reader.cancel();
                throw new ApiError(413, "PAYLOAD_TOO_LARGE", "MCP 请求超过 600 KB 限制");
            }
            chunks.push(value);
        }
    } finally {
        reader.releaseLock();
    }
    const bytes = new Uint8Array(size);
    let offset = 0;
    for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; }
    return JSON.parse(new TextDecoder().decode(bytes));
}

function responseHeaders(response: Response, request: Request, env: Bindings): Response {
    const headers = new Headers(response.headers);
    headers.set("Cache-Control", "no-store");
    headers.set("X-Content-Type-Options", "nosniff");
    headers.set("Referrer-Policy", "no-referrer");
    headers.set("Vary", "Origin");
    if (response.status === 401) headers.set("WWW-Authenticate", 'Bearer realm="FlowMaster"');
    if (response.status === 429) headers.set("Retry-After", "60");
    if (response.status === 405) headers.set("Allow", "POST, OPTIONS");
    const origin = request.headers.get("Origin");
    const allowed = (env.ALLOWED_ORIGINS || "").split(",").map(value => value.trim()).filter(Boolean);
    if (origin && (origin === new URL(request.url).origin || allowed.includes(origin))) {
        headers.set("Access-Control-Allow-Origin", origin);
        headers.set("Access-Control-Allow-Methods", "POST, OPTIONS");
        headers.set("Access-Control-Allow-Headers", "Authorization, Content-Type, Accept, MCP-Protocol-Version, Mcp-Session-Id");
        headers.set("Access-Control-Expose-Headers", "MCP-Protocol-Version, Mcp-Session-Id, WWW-Authenticate, Retry-After");
        headers.set("Access-Control-Max-Age", "600");
    }
    return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}

export async function handleMcp(request: Request, env: Bindings): Promise<Response> {
    let response: Response;
    let server: McpServer | undefined;
    try {
        validateOrigin(request, env);
        if (request.method === "OPTIONS") return responseHeaders(new Response(null, { status: 204 }), request, env);
        // Authenticate every HTTP request, including discovery and initialization.
        // Principals and SDK transports are never shared between requests/users.
        const principal = await authorizeRequest(request, env);
        if (request.method !== "POST") return responseHeaders(rpcError(405, -32000, "Use POST for the stateless MCP endpoint"), request, env);
        const contentType = request.headers.get("Content-Type")?.split(";", 1)[0].trim().toLowerCase();
        if (contentType !== "application/json") return responseHeaders(rpcError(415, -32000, "Content-Type must be application/json"), request, env);
        const message = await readMessage(request);
        // MCP 2025-06-18+ removed batching. One message per request also keeps
        // rate limiting and token revocation checks scoped to each operation.
        if (Array.isArray(message)) return responseHeaders(rpcError(400, -32600, "JSON-RPC batches are not supported"), request, env);
        // MCP permits omitted arguments. Supply the empty object before the
        // SDK validates tool inputs, preserving each tool's discovery schema.
        if (message && typeof message === "object" && "method" in message && message.method === "tools/call" && "params" in message) {
            const params = message.params;
            if (params && typeof params === "object" && !Array.isArray(params) && !Object.hasOwn(params, "arguments")) {
                Object.assign(params, { arguments: {} });
            }
        }
        server = createServer(request, env, principal);
        const transport = new WebStandardStreamableHTTPServerTransport({ sessionIdGenerator: undefined, enableJsonResponse: true, maxRequestBodySize: maxBodyBytes });
        await server.connect(transport);
        response = await transport.handleRequest(request, { parsedBody: message });
    } catch (error) {
        if (error instanceof SyntaxError) response = rpcError(400, -32700, "Invalid JSON");
        else if (error instanceof ApiError) response = rpcError(error.status, -32000, error.message, { code: error.code });
        else {
            console.error("FlowMaster MCP failure", error instanceof Error ? error.name : "unknown");
            response = rpcError(500, -32603, "服务暂时不可用，请检查数据库迁移或稍后重试");
        }
    } finally {
        // JSON-mode responses have completed before handleRequest resolves.
        await server?.close();
    }
    return responseHeaders(response, request, env);
}
